# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages_tracker_detection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages_tracker_detection.proto',
  package='',
  serialized_pb=_b('\n messages_tracker_detection.proto\"j\n\x15TRACKER_DetectionBall\x12\x12\n\nconfidence\x18\x01 \x02(\x02\x12\x0f\n\x07\x62\x61ll_id\x18\x02 \x02(\r\x12\t\n\x01x\x18\x03 \x02(\x02\x12\t\n\x01y\x18\x04 \x02(\x02\x12\n\n\x02vx\x18\x05 \x02(\x02\x12\n\n\x02vy\x18\x06 \x02(\x02\"\x98\x01\n\x16TRACKER_DetectionRobot\x12\x12\n\nconfidence\x18\x01 \x02(\x02\x12\x10\n\x08robot_id\x18\x02 \x02(\r\x12\t\n\x01x\x18\x03 \x02(\x02\x12\t\n\x01y\x18\x04 \x02(\x02\x12\n\n\x02vx\x18\x05 \x02(\x02\x12\n\n\x02vy\x18\x06 \x02(\x02\x12\x13\n\x0borientation\x18\x07 \x02(\x02\x12\x15\n\rangular_speed\x18\x08 \x02(\x02\"\xa7\x01\n\x11TRACKER_Detection\x12\x11\n\ttimestamp\x18\x01 \x02(\x01\x12%\n\x05\x62\x61lls\x18\x02 \x03(\x0b\x32\x16.TRACKER_DetectionBall\x12,\n\x0byellow_team\x18\x03 \x03(\x0b\x32\x17.TRACKER_DetectionRobot\x12*\n\tblue_team\x18\x04 \x03(\x0b\x32\x17.TRACKER_DetectionRobot')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRACKER_DETECTIONBALL = _descriptor.Descriptor(
  name='TRACKER_DetectionBall',
  full_name='TRACKER_DetectionBall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence', full_name='TRACKER_DetectionBall.confidence', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ball_id', full_name='TRACKER_DetectionBall.ball_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='TRACKER_DetectionBall.x', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='TRACKER_DetectionBall.y', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vx', full_name='TRACKER_DetectionBall.vx', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vy', full_name='TRACKER_DetectionBall.vy', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=142,
)


_TRACKER_DETECTIONROBOT = _descriptor.Descriptor(
  name='TRACKER_DetectionRobot',
  full_name='TRACKER_DetectionRobot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence', full_name='TRACKER_DetectionRobot.confidence', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='TRACKER_DetectionRobot.robot_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='TRACKER_DetectionRobot.x', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='TRACKER_DetectionRobot.y', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vx', full_name='TRACKER_DetectionRobot.vx', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vy', full_name='TRACKER_DetectionRobot.vy', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='TRACKER_DetectionRobot.orientation', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular_speed', full_name='TRACKER_DetectionRobot.angular_speed', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=297,
)


_TRACKER_DETECTION = _descriptor.Descriptor(
  name='TRACKER_Detection',
  full_name='TRACKER_Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TRACKER_Detection.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='balls', full_name='TRACKER_Detection.balls', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yellow_team', full_name='TRACKER_Detection.yellow_team', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blue_team', full_name='TRACKER_Detection.blue_team', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=467,
)

_TRACKER_DETECTION.fields_by_name['balls'].message_type = _TRACKER_DETECTIONBALL
_TRACKER_DETECTION.fields_by_name['yellow_team'].message_type = _TRACKER_DETECTIONROBOT
_TRACKER_DETECTION.fields_by_name['blue_team'].message_type = _TRACKER_DETECTIONROBOT
DESCRIPTOR.message_types_by_name['TRACKER_DetectionBall'] = _TRACKER_DETECTIONBALL
DESCRIPTOR.message_types_by_name['TRACKER_DetectionRobot'] = _TRACKER_DETECTIONROBOT
DESCRIPTOR.message_types_by_name['TRACKER_Detection'] = _TRACKER_DETECTION

TRACKER_DetectionBall = _reflection.GeneratedProtocolMessageType('TRACKER_DetectionBall', (_message.Message,), dict(
  DESCRIPTOR = _TRACKER_DETECTIONBALL,
  __module__ = 'messages_tracker_detection_pb2'
  # @@protoc_insertion_point(class_scope:TRACKER_DetectionBall)
  ))
_sym_db.RegisterMessage(TRACKER_DetectionBall)

TRACKER_DetectionRobot = _reflection.GeneratedProtocolMessageType('TRACKER_DetectionRobot', (_message.Message,), dict(
  DESCRIPTOR = _TRACKER_DETECTIONROBOT,
  __module__ = 'messages_tracker_detection_pb2'
  # @@protoc_insertion_point(class_scope:TRACKER_DetectionRobot)
  ))
_sym_db.RegisterMessage(TRACKER_DetectionRobot)

TRACKER_Detection = _reflection.GeneratedProtocolMessageType('TRACKER_Detection', (_message.Message,), dict(
  DESCRIPTOR = _TRACKER_DETECTION,
  __module__ = 'messages_tracker_detection_pb2'
  # @@protoc_insertion_point(class_scope:TRACKER_Detection)
  ))
_sym_db.RegisterMessage(TRACKER_Detection)


# @@protoc_insertion_point(module_scope)
