# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages_tracker_wrapper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages_tracker_detection_pb2
import messages_tracker_geometry_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages_tracker_wrapper.proto',
  package='',
  serialized_pb=_b('\n\x1emessages_tracker_wrapper.proto\x1a messages_tracker_detection.proto\x1a\x1fmessages_tracker_geometry.proto\"c\n\x15TRACKER_WrapperPacket\x12%\n\tdetection\x18\x01 \x01(\x0b\x32\x12.TRACKER_Detection\x12#\n\x08geometry\x18\x02 \x01(\x0b\x32\x11.TRACKER_Geometry')
  ,
  dependencies=[messages_tracker_detection_pb2.DESCRIPTOR,messages_tracker_geometry_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRACKER_WRAPPERPACKET = _descriptor.Descriptor(
  name='TRACKER_WrapperPacket',
  full_name='TRACKER_WrapperPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detection', full_name='TRACKER_WrapperPacket.detection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='TRACKER_WrapperPacket.geometry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=200,
)

_TRACKER_WRAPPERPACKET.fields_by_name['detection'].message_type = messages_tracker_detection_pb2._TRACKER_DETECTION
_TRACKER_WRAPPERPACKET.fields_by_name['geometry'].message_type = messages_tracker_geometry_pb2._TRACKER_GEOMETRY
DESCRIPTOR.message_types_by_name['TRACKER_WrapperPacket'] = _TRACKER_WRAPPERPACKET

TRACKER_WrapperPacket = _reflection.GeneratedProtocolMessageType('TRACKER_WrapperPacket', (_message.Message,), dict(
  DESCRIPTOR = _TRACKER_WRAPPERPACKET,
  __module__ = 'messages_tracker_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:TRACKER_WrapperPacket)
  ))
_sym_db.RegisterMessage(TRACKER_WrapperPacket)


# @@protoc_insertion_point(module_scope)
